# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uczelnia1.ui'
#
# Created: Wed Jun 25 12:45:22 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1038, 600)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.newStudentsTab = QtGui.QTabWidget(Dialog)
        self.newStudentsTab.setEnabled(True)
        self.newStudentsTab.setGeometry(QtCore.QRect(90, 100, 708, 343))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newStudentsTab.sizePolicy().hasHeightForWidth())
        self.newStudentsTab.setSizePolicy(sizePolicy)
        self.newStudentsTab.setObjectName(_fromUtf8("newStudentsTab"))
        self.R = QtGui.QWidget()
        self.R.setObjectName(_fromUtf8("R"))
        self.newStudentsTab.addTab(self.R, _fromUtf8(""))
        self.Wykladowcy = QtGui.QWidget()
        self.Wykladowcy.setObjectName(_fromUtf8("Wykladowcy"))
        self.layoutWidget = QtGui.QWidget(self.Wykladowcy)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 686, 258))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalScrollBarOfLecturersList = QtGui.QScrollBar(self.layoutWidget)
        self.verticalScrollBarOfLecturersList.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarOfLecturersList.setObjectName(_fromUtf8("verticalScrollBarOfLecturersList"))
        self.horizontalLayout_9.addWidget(self.verticalScrollBarOfLecturersList)
        self.tableWidgetLecturer = QtGui.QTableWidget(self.layoutWidget)
        self.tableWidgetLecturer.setObjectName(_fromUtf8("tableWidgetLecturer"))
        self.tableWidgetLecturer.setColumnCount(0)
        self.tableWidgetLecturer.setRowCount(0)
        self.horizontalLayout_9.addWidget(self.tableWidgetLecturer)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lecturerInformationsLabel_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lecturerInformationsLabel_3.sizePolicy().hasHeightForWidth())
        self.lecturerInformationsLabel_3.setSizePolicy(sizePolicy)
        self.lecturerInformationsLabel_3.setMaximumSize(QtCore.QSize(16777215, 16766643))
        self.lecturerInformationsLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lecturerInformationsLabel_3.setObjectName(_fromUtf8("lecturerInformationsLabel_3"))
        self.verticalLayout_7.addWidget(self.lecturerInformationsLabel_3)
        self.lecturerFirstNameField_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lecturerFirstNameField_3.setObjectName(_fromUtf8("lecturerFirstNameField_3"))
        self.verticalLayout_7.addWidget(self.lecturerFirstNameField_3)
        self.lecturerSureNameField_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lecturerSureNameField_3.setObjectName(_fromUtf8("lecturerSureNameField_3"))
        self.verticalLayout_7.addWidget(self.lecturerSureNameField_3)
        self.lecturerPeselNameField_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lecturerPeselNameField_3.setObjectName(_fromUtf8("lecturerPeselNameField_3"))
        self.verticalLayout_7.addWidget(self.lecturerPeselNameField_3)
        self.lecturerAdressField_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lecturerAdressField_3.setObjectName(_fromUtf8("lecturerAdressField_3"))
        self.verticalLayout_7.addWidget(self.lecturerAdressField_3)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_10.addLayout(self.verticalLayout_12)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_10)
        self.studentEditDataButton_2 = QtGui.QPushButton(self.Wykladowcy)
        self.studentEditDataButton_2.setGeometry(QtCore.QRect(10, 280, 686, 27))
        self.studentEditDataButton_2.setObjectName(_fromUtf8("studentEditDataButton_2"))
        self.newStudentsTab.addTab(self.Wykladowcy, _fromUtf8(""))
        self.Studenci = QtGui.QWidget()
        self.Studenci.setObjectName(_fromUtf8("Studenci"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Studenci)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalScrollBarOfStudentsList = QtGui.QScrollBar(self.Studenci)
        self.verticalScrollBarOfStudentsList.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarOfStudentsList.setObjectName(_fromUtf8("verticalScrollBarOfStudentsList"))
        self.horizontalLayout_3.addWidget(self.verticalScrollBarOfStudentsList)
        self.tableWidget = QtGui.QTableWidget(self.Studenci)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.studentInformationsLabel = QtGui.QLabel(self.Studenci)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentInformationsLabel.sizePolicy().hasHeightForWidth())
        self.studentInformationsLabel.setSizePolicy(sizePolicy)
        self.studentInformationsLabel.setMaximumSize(QtCore.QSize(16777215, 16766643))
        self.studentInformationsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.studentInformationsLabel.setObjectName(_fromUtf8("studentInformationsLabel"))
        self.verticalLayout_3.addWidget(self.studentInformationsLabel)
        self.studentIndexNumberField = QtGui.QLineEdit(self.Studenci)
        self.studentIndexNumberField.setObjectName(_fromUtf8("studentIndexNumberField"))
        self.verticalLayout_3.addWidget(self.studentIndexNumberField)
        self.studentFirstNameField = QtGui.QLineEdit(self.Studenci)
        self.studentFirstNameField.setObjectName(_fromUtf8("studentFirstNameField"))
        self.verticalLayout_3.addWidget(self.studentFirstNameField)
        self.studentSureNameField = QtGui.QLineEdit(self.Studenci)
        self.studentSureNameField.setObjectName(_fromUtf8("studentSureNameField"))
        self.verticalLayout_3.addWidget(self.studentSureNameField)
        self.studentPeselNameField = QtGui.QLineEdit(self.Studenci)
        self.studentPeselNameField.setObjectName(_fromUtf8("studentPeselNameField"))
        self.verticalLayout_3.addWidget(self.studentPeselNameField)
        self.studentAdressField = QtGui.QLineEdit(self.Studenci)
        self.studentAdressField.setObjectName(_fromUtf8("studentAdressField"))
        self.verticalLayout_3.addWidget(self.studentAdressField)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.studentGroupLabel = QtGui.QLabel(self.Studenci)
        self.studentGroupLabel.setObjectName(_fromUtf8("studentGroupLabel"))
        self.horizontalLayout_6.addWidget(self.studentGroupLabel)
        self.studentGroupDropdownList = QtGui.QComboBox(self.Studenci)
        self.studentGroupDropdownList.setEditable(False)
        self.studentGroupDropdownList.setInsertPolicy(QtGui.QComboBox.InsertAfterCurrent)
        self.studentGroupDropdownList.setFrame(True)
        self.studentGroupDropdownList.setObjectName(_fromUtf8("studentGroupDropdownList"))
        self.studentGroupDropdownList.addItem(_fromUtf8(""))
        self.studentGroupDropdownList.addItem(_fromUtf8(""))
        self.studentGroupDropdownList.addItem(_fromUtf8(""))
        self.studentGroupDropdownList.addItem(_fromUtf8(""))
        self.studentGroupDropdownList.addItem(_fromUtf8(""))
        self.studentGroupDropdownList.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.studentGroupDropdownList)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.studentYearLabel = QtGui.QLabel(self.Studenci)
        self.studentYearLabel.setObjectName(_fromUtf8("studentYearLabel"))
        self.horizontalLayout_5.addWidget(self.studentYearLabel)
        self.studentYearDropdownList = QtGui.QComboBox(self.Studenci)
        self.studentYearDropdownList.setEditable(False)
        self.studentYearDropdownList.setInsertPolicy(QtGui.QComboBox.InsertAfterCurrent)
        self.studentYearDropdownList.setFrame(True)
        self.studentYearDropdownList.setObjectName(_fromUtf8("studentYearDropdownList"))
        self.studentYearDropdownList.addItem(_fromUtf8(""))
        self.studentYearDropdownList.addItem(_fromUtf8(""))
        self.studentYearDropdownList.addItem(_fromUtf8(""))
        self.studentYearDropdownList.addItem(_fromUtf8(""))
        self.studentYearDropdownList.addItem(_fromUtf8(""))
        self.studentYearDropdownList.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.studentYearDropdownList)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.studentEditDataButton = QtGui.QPushButton(self.Studenci)
        self.studentEditDataButton.setObjectName(_fromUtf8("studentEditDataButton"))
        self.verticalLayout_5.addWidget(self.studentEditDataButton)
        self.newStudentsTab.addTab(self.Studenci, _fromUtf8(""))
        self.NowyStudent = QtGui.QWidget()
        self.NowyStudent.setObjectName(_fromUtf8("NowyStudent"))
        self.layoutWidget_2 = QtGui.QWidget(self.NowyStudent)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 686, 281))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.newStudentInformationsLabel_2 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newStudentInformationsLabel_2.sizePolicy().hasHeightForWidth())
        self.newStudentInformationsLabel_2.setSizePolicy(sizePolicy)
        self.newStudentInformationsLabel_2.setMaximumSize(QtCore.QSize(16777215, 16766643))
        self.newStudentInformationsLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.newStudentInformationsLabel_2.setObjectName(_fromUtf8("newStudentInformationsLabel_2"))
        self.verticalLayout_9.addWidget(self.newStudentInformationsLabel_2)
        self.newStudentFirstNameField = QtGui.QLineEdit(self.layoutWidget_2)
        self.newStudentFirstNameField.setObjectName(_fromUtf8("newStudentFirstNameField"))
        self.verticalLayout_9.addWidget(self.newStudentFirstNameField)
        self.newStudentSureNameField = QtGui.QLineEdit(self.layoutWidget_2)
        self.newStudentSureNameField.setObjectName(_fromUtf8("newStudentSureNameField"))
        self.verticalLayout_9.addWidget(self.newStudentSureNameField)
        self.newStudentPeselNameField = QtGui.QLineEdit(self.layoutWidget_2)
        self.newStudentPeselNameField.setObjectName(_fromUtf8("newStudentPeselNameField"))
        self.verticalLayout_9.addWidget(self.newStudentPeselNameField)
        self.newStudentAdressField = QtGui.QLineEdit(self.layoutWidget_2)
        self.newStudentAdressField.setObjectName(_fromUtf8("newStudentAdressField"))
        self.verticalLayout_9.addWidget(self.newStudentAdressField)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.newStudentYearLabel = QtGui.QLabel(self.layoutWidget_2)
        self.newStudentYearLabel.setObjectName(_fromUtf8("newStudentYearLabel"))
        self.horizontalLayout_14.addWidget(self.newStudentYearLabel)
        self.newStudentYearDropdownList = QtGui.QComboBox(self.layoutWidget_2)
        self.newStudentYearDropdownList.setEditable(False)
        self.newStudentYearDropdownList.setInsertPolicy(QtGui.QComboBox.InsertAfterCurrent)
        self.newStudentYearDropdownList.setFrame(True)
        self.newStudentYearDropdownList.setObjectName(_fromUtf8("newStudentYearDropdownList"))
        self.newStudentYearDropdownList.addItem(_fromUtf8(""))
        self.newStudentYearDropdownList.addItem(_fromUtf8(""))
        self.newStudentYearDropdownList.addItem(_fromUtf8(""))
        self.newStudentYearDropdownList.addItem(_fromUtf8(""))
        self.newStudentYearDropdownList.addItem(_fromUtf8(""))
        self.newStudentYearDropdownList.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.newStudentYearDropdownList)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        self.newStudentGroupLabel = QtGui.QLabel(self.layoutWidget_2)
        self.newStudentGroupLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.newStudentGroupLabel.setObjectName(_fromUtf8("newStudentGroupLabel"))
        self.horizontalLayout_13.addWidget(self.newStudentGroupLabel)
        self.newStudentGroupDropdownList = QtGui.QComboBox(self.layoutWidget_2)
        self.newStudentGroupDropdownList.setEditable(False)
        self.newStudentGroupDropdownList.setInsertPolicy(QtGui.QComboBox.InsertAfterCurrent)
        self.newStudentGroupDropdownList.setFrame(True)
        self.newStudentGroupDropdownList.setObjectName(_fromUtf8("newStudentGroupDropdownList"))
        self.newStudentGroupDropdownList.addItem(_fromUtf8(""))
        self.newStudentGroupDropdownList.addItem(_fromUtf8(""))
        self.newStudentGroupDropdownList.addItem(_fromUtf8(""))
        self.newStudentGroupDropdownList.addItem(_fromUtf8(""))
        self.newStudentGroupDropdownList.addItem(_fromUtf8(""))
        self.newStudentGroupDropdownList.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.newStudentGroupDropdownList)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.newStudentSubmitButton = QtGui.QPushButton(self.layoutWidget_2)
        self.newStudentSubmitButton.setObjectName(_fromUtf8("newStudentSubmitButton"))
        self.verticalLayout_9.addWidget(self.newStudentSubmitButton)
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.studentStatusFrame_2 = QtGui.QFrame(self.layoutWidget_2)
        self.studentStatusFrame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.studentStatusFrame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.studentStatusFrame_2.setObjectName(_fromUtf8("studentStatusFrame_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.studentStatusFrame_2)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_10.addWidget(self.studentStatusFrame_2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_10)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_12)
        self.newStudentsTab.addTab(self.NowyStudent, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(20, 20, 671, 271))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalScrollBar = QtGui.QScrollBar(self.widget)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName(_fromUtf8("verticalScrollBar"))
        self.horizontalLayout_16.addWidget(self.verticalScrollBar)
        self.tableWidgetSubjects = QtGui.QTableWidget(self.widget)
        self.tableWidgetSubjects.setObjectName(_fromUtf8("tableWidgetSubjects"))
        self.tableWidgetSubjects.setColumnCount(0)
        self.tableWidgetSubjects.setRowCount(0)
        self.horizontalLayout_16.addWidget(self.tableWidgetSubjects)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.newSubjectButton = QtGui.QPushButton(self.widget)
        self.newSubjectButton.setObjectName(_fromUtf8("newSubjectButton"))
        self.horizontalLayout.addWidget(self.newSubjectButton)
        self.newSubjectField = QtGui.QLineEdit(self.widget)
        self.newSubjectField.setObjectName(_fromUtf8("newSubjectField"))
        self.horizontalLayout.addWidget(self.newSubjectField)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.newStudentsTab.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.newStudentsTab.setCurrentIndex(4)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.newStudentsTab.setTabText(self.newStudentsTab.indexOf(self.R), _translate("Dialog", "Rocznik", None))
        self.lecturerInformationsLabel_3.setText(_translate("Dialog", "Dane wykładowcy", None))
        self.lecturerFirstNameField_3.setPlaceholderText(_translate("Dialog", "Imię", None))
        self.lecturerSureNameField_3.setPlaceholderText(_translate("Dialog", "Nazwisko", None))
        self.lecturerPeselNameField_3.setPlaceholderText(_translate("Dialog", "PESEL", None))
        self.lecturerAdressField_3.setPlaceholderText(_translate("Dialog", "Adres Zamieszkania", None))
        self.studentEditDataButton_2.setText(_translate("Dialog", "Edytuj zmiany", None))
        self.newStudentsTab.setTabText(self.newStudentsTab.indexOf(self.Wykladowcy), _translate("Dialog", "Wykładowcy", None))
        self.studentInformationsLabel.setText(_translate("Dialog", "Dane studenta", None))
        self.studentIndexNumberField.setPlaceholderText(_translate("Dialog", "Index", None))
        self.studentFirstNameField.setPlaceholderText(_translate("Dialog", "Imię", None))
        self.studentSureNameField.setPlaceholderText(_translate("Dialog", "Nazwisko", None))
        self.studentPeselNameField.setPlaceholderText(_translate("Dialog", "PESEL", None))
        self.studentAdressField.setPlaceholderText(_translate("Dialog", "Adres Zamieszkania", None))
        self.studentGroupLabel.setText(_translate("Dialog", "Grupa", None))
        self.studentGroupDropdownList.setProperty("currentText", _translate("Dialog", "sacasc", None))
        self.studentGroupDropdownList.setItemText(0, _translate("Dialog", "sacasc", None))
        self.studentGroupDropdownList.setItemText(1, _translate("Dialog", "sacasc", None))
        self.studentGroupDropdownList.setItemText(2, _translate("Dialog", "ascascas", None))
        self.studentGroupDropdownList.setItemText(3, _translate("Dialog", "cascasca", None))
        self.studentGroupDropdownList.setItemText(4, _translate("Dialog", "scascasc", None))
        self.studentGroupDropdownList.setItemText(5, _translate("Dialog", "ascascasc", None))
        self.studentYearLabel.setText(_translate("Dialog", "Rocznik", None))
        self.studentYearDropdownList.setProperty("currentText", _translate("Dialog", "sacasc", None))
        self.studentYearDropdownList.setItemText(0, _translate("Dialog", "sacasc", None))
        self.studentYearDropdownList.setItemText(1, _translate("Dialog", "sacasc", None))
        self.studentYearDropdownList.setItemText(2, _translate("Dialog", "ascascas", None))
        self.studentYearDropdownList.setItemText(3, _translate("Dialog", "cascasca", None))
        self.studentYearDropdownList.setItemText(4, _translate("Dialog", "scascasc", None))
        self.studentYearDropdownList.setItemText(5, _translate("Dialog", "ascascasc", None))
        self.studentEditDataButton.setText(_translate("Dialog", "Edytuj zmiany", None))
        self.newStudentsTab.setTabText(self.newStudentsTab.indexOf(self.Studenci), _translate("Dialog", "Studenci", None))
        self.newStudentInformationsLabel_2.setText(_translate("Dialog", "Dane studenta", None))
        self.newStudentFirstNameField.setPlaceholderText(_translate("Dialog", "Imię", None))
        self.newStudentSureNameField.setPlaceholderText(_translate("Dialog", "Nazwisko", None))
        self.newStudentPeselNameField.setPlaceholderText(_translate("Dialog", "PESEL", None))
        self.newStudentAdressField.setPlaceholderText(_translate("Dialog", "Adres Zamieszkania", None))
        self.newStudentYearLabel.setText(_translate("Dialog", "Rocznik", None))
        self.newStudentYearDropdownList.setProperty("currentText", _translate("Dialog", "sacasc", None))
        self.newStudentYearDropdownList.setItemText(0, _translate("Dialog", "sacasc", None))
        self.newStudentYearDropdownList.setItemText(1, _translate("Dialog", "sacasc", None))
        self.newStudentYearDropdownList.setItemText(2, _translate("Dialog", "ascascas", None))
        self.newStudentYearDropdownList.setItemText(3, _translate("Dialog", "cascasca", None))
        self.newStudentYearDropdownList.setItemText(4, _translate("Dialog", "scascasc", None))
        self.newStudentYearDropdownList.setItemText(5, _translate("Dialog", "ascascasc", None))
        self.newStudentGroupLabel.setText(_translate("Dialog", "Grupa", None))
        self.newStudentGroupDropdownList.setProperty("currentText", _translate("Dialog", "sacasc", None))
        self.newStudentGroupDropdownList.setItemText(0, _translate("Dialog", "sacasc", None))
        self.newStudentGroupDropdownList.setItemText(1, _translate("Dialog", "sacasc", None))
        self.newStudentGroupDropdownList.setItemText(2, _translate("Dialog", "ascascas", None))
        self.newStudentGroupDropdownList.setItemText(3, _translate("Dialog", "cascasca", None))
        self.newStudentGroupDropdownList.setItemText(4, _translate("Dialog", "scascasc", None))
        self.newStudentGroupDropdownList.setItemText(5, _translate("Dialog", "ascascasc", None))
        self.newStudentSubmitButton.setText(_translate("Dialog", "Zapisz", None))
        self.newStudentsTab.setTabText(self.newStudentsTab.indexOf(self.NowyStudent), _translate("Dialog", "Nowy student", None))
        self.newSubjectButton.setText(_translate("Dialog", "Nowy przedmiot", None))
        self.newStudentsTab.setTabText(self.newStudentsTab.indexOf(self.tab), _translate("Dialog", "Przedmioty", None))

